apiVersion: v1
kind: Service
metadata:
  name: infra-browser-service
  namespace: model-dev
  labels:
    app: browser
    tier: infra
spec:
  selector:
    app: browser
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: infra-browser-ingress
  namespace: model-dev
  labels:
    tier: infra
  annotations:
    haproxy.org/forwarded-for: "enabled"
    haproxy.org/request-set-header: "X-Forwarded-Proto https"
spec:
  ingressClassName: haproxy
  tls:
  - hosts:
    - files-model-dev.nrp-nautilus.io
  rules:
  - host: files-model-dev.nrp-nautilus.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: infra-browser-service
            port:
              number: 80
