apiVersion: v1
kind: Service
metadata:
  name: infra-jupyter-service
  namespace: model-dev
  labels:
    app: jupyter
    tier: infra
spec:
  selector:
    app: jupyter
  ports:
  - name: http
    protocol: TCP
    port: 8888
    targetPort: 8888
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: infra-jupyter-ingress
  namespace: model-dev
  labels:
    tier: infra
  annotations:
    haproxy.org/auth-url: "https://auth-model-dev.nrp-nautilus.io/api/verify?rd=https://jupyter-model-dev.nrp-nautilus.io"
    haproxy.org/auth-signin: "https://auth-model-dev.nrp-nautilus.io/?rd=https://jupyter-model-dev.nrp-nautilus.io"
    ingress.kubernetes.io/auth-url: "https://auth-model-dev.nrp-nautilus.io/api/verify?rd=https://jupyter-model-dev.nrp-nautilus.io"
    ingress.kubernetes.io/auth-signin: "https://auth-model-dev.nrp-nautilus.io/?rd=https://jupyter-model-dev.nrp-nautilus.io"
spec:
  ingressClassName: haproxy
  tls:
  - hosts:
    - jupyter-model-dev.nrp-nautilus.io
  rules:
  - host: jupyter-model-dev.nrp-nautilus.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: infra-jupyter-service
            port:
              number: 8888
