apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: infra-datasets-pvc
  namespace: model-dev
  labels:
    type: datasets
    tier: infra
spec:
  storageClassName: rook-cephfs-ucsd
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Ti
