apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: infra-registry-pvc
  namespace: model-dev
  labels:
    app: registry
    tier: infra
spec:
  storageClassName: rook-cephfs-ucsd
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi

